[package]
name = "zoglin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
glob = "0.3.1"
json5 = "0.4.1"
serde = { version = "1.0.198", features = ["derive"] }
serde_json = "1.0.116"
