site_name: Zoglin Docs
site_url: https://zoglin.dev/
repo_url: https://github.com/GMDU/zoglin/
theme:
  name: material
  palette: 
    scheme: slate
    primary: deep purple
    accent: purple
  features:
    - navigation.top
    - navigation.footer
    - navigation.indexes
markdown_extensions:
  - attr_list
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true
extra:
  parent_site: /
  social:
    - icon: simple/discord
      link: https://datapack.dev/discord
    - icon: simple/github
      link: https://github.com/GMDU
extra_css:
  - stylesheets/extra.css
nav:
  - 'index.md'
  - 'faq.md'
  - 'getting-started.md'
  - Zoglin:
    - 'zoglin/project-structure.md'
    - 'zoglin/functions.md'
    - 'zoglin/resources.md'
    - 'zoglin/variables.md'
    - 'zoglin/compile-time.md'
