use super::token::TokenKind;

pub const COMMANDS: &[&str] = &[
  "advancement",
  "attribute",
  "bossbar",
  "clear",
  "clone",
  "damage",
  "data",
  "datapack",
  "difficulty",
  "effect",
  "enchant",
  "execute",
  "experience",
  "fill",
  "fillbiome",
  "forceload",
  "function",
  "gamemode",
  "gamerule",
  "give",
  "item",
  "kill",
  "loot",
  "particle",
  "place",
  "playsound",
  "random",
  "recipe",
  "reload",
  "ride",
  "say",
  "schedule",
  "scoreboard",
  "setblock",
  "setworldspawn",
  "spawnpoint",
  "spectate",
  "spreadplayers",
  "stopsound",
  "summon",
  "tag",
  "team",
  "teleport",
  "tellraw",
  "time",
  "title",
  "tp",
  "trigger",
  "weather",
  "worldborder",
  "xp",
];

pub const OPERATOR_REGISTRY: &[(&str, TokenKind)] = &[
  ("(", TokenKind::LeftParen),
  (")", TokenKind::RightParen),
  ("[", TokenKind::LeftSquare),
  ("]", TokenKind::RightSquare),
  ("{", TokenKind::LeftBrace),
  ("}", TokenKind::RightBrace),
  ("/", TokenKind::ForwardSlash),
  (":", TokenKind::Colon),
  (".", TokenKind::Dot),
  ("..", TokenKind::DoubleDot),
  (";", TokenKind::Semicolon),
  (",", TokenKind::Comma),
  ("+", TokenKind::Plus),
  ("-", TokenKind::Minus),
  ("*", TokenKind::Star),
  ("%", TokenKind::Percent),
  ("**", TokenKind::DoubleStar),
  ("<<", TokenKind::LeftShift),
  (">>", TokenKind::RightShift),
  ("<", TokenKind::LessThan),
  (">", TokenKind::GreaterThan),
  ("<=", TokenKind::LessThanEquals),
  (">=", TokenKind::GreaterThanEquals),
  ("==", TokenKind::DoubleEquals),
  ("!=", TokenKind::BangEquals),
  ("&", TokenKind::Ampersand),
  ("&&", TokenKind::DoubleAmpersand),
  ("||", TokenKind::DoublePipe),
  ("!", TokenKind::Bang),
  ("~", TokenKind::Tilde),
  ("=", TokenKind::Equals),
  ("+=", TokenKind::PlusEquals),
  ("-=", TokenKind::MinusEquals),
  ("*=", TokenKind::StarEquals),
  ("/=", TokenKind::ForwardSlashEquals),
  ("%=", TokenKind::PercentEquals),
  ("$", TokenKind::Dollar),
];

pub const KEYWORD_REGISTRY: &[(&str, TokenKind)] = &[
  ("namespace", TokenKind::NamespaceKeyword),
  ("module", TokenKind::ModuleKeyword),
  ("fn", TokenKind::FunctionKeyword),
  ("res", TokenKind::ResourceKeyword),
  ("asset", TokenKind::AssetKeyword),
  ("include", TokenKind::IncludeKeyword),
  ("import", TokenKind::ImportKeyword),
  ("as", TokenKind::AsKeyword),
  ("if", TokenKind::IfKeyword),
  ("else", TokenKind::ElseKeyword),
  ("while", TokenKind::WhileKeyword),
  ("true", TokenKind::TrueKeyword),
  ("false", TokenKind::FalseKeyword),
  ("return", TokenKind::ReturnKeyword),
];
