use error::Location;
use crate::error;

#[derive(Debug, Clone)]

pub struct Token {
  pub kind: TokenKind,
  pub value: String,
  pub location: Location,
}

#[derive(PartialEq, Debug, Clone)]
pub enum TokenKind {
  EndOfFile,
  EndOfInclude,
  NamespaceKeyword,
  FunctionKeyword,
  ModuleKeyword,
  ResourceKeyword,
  AssetKeyword,
  IncludeKeyword,
  ImportKeyword,
  AsKeyword,
  CommandBegin,
  CommandString,
  CommandEnd,
  Comment,
  Identifier,
  LeftBrace,
  RightBrace,
  LeftSquare,
  RightSquare,
  LeftParen,
  RightParen,
  ForwardSlash,
  Colon,
  Dot,
  Integer,
  JSON,
  String,
  Plus,
  Minus,
  Star,
  Percent,
  DoubleStar,
  LeftShift,
  RightShift,
  LessThan,
  GreaterThan,
  LessThanEquals,
  GreaterThanEquals,
  DoubleEquals,
  BangEquals,
  DoubleAmpersand,
  DoublePipe,
  Bang,
  Equals,
  PlusEquals,
  MinusEquals,
  StarEquals,
  ForwardSlashEquals,
  PercentEquals,
}